# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Projects/frodo-fpga/frodo-fpga.runs/synth_1/.Xil/Vivado-18240-Vinicius-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8c62/hdl
    c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/ec67/hdl
  } {
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8c62/hdl
    c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/ec67/hdl
  } {
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_processing_system7_0_0/synth/frodoBD_processing_system7_0_0.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_xbar_0/synth/frodoBD_xbar_0.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_auto_pc_0/synth/frodoBD_auto_pc_0.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      C:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/hdl/frodoBD_wrapper.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_proc_sys_reset_0_0/synth/frodoBD_proc_sys_reset_0_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_axi_gpio_1_0/synth/frodoBD_axi_gpio_1_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_axi_fifo_mm_s_0_0/synth/frodoBD_axi_fifo_mm_s_0_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_axi_gpio_2_0/synth/frodoBD_axi_gpio_2_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/ea3f/hdl/timer_v1_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_timer_0_2/synth/frodoBD_timer_0_2.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/7d49/hdl/keccak_f1600_core.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/7d49/hdl/keccak_f1600_ip_v1_0_M00_AXIS.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/7d49/hdl/keccak_f1600_ip_v1_0_S00_AXIS.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/7d49/hdl/keccak_f1600_ip_v1_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_keccak_f1600_ip_0_0/synth/frodoBD_keccak_f1600_ip_0_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/355c/hdl/keccak_f1600_mm_core.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/355c/hdl/keccak_f1600_mm_ip_v1_0_S00_AXI.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/355c/hdl/keccak_f1600_mm_ip_v1_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_keccak_f1600_mm_ip_0_0/synth/frodoBD_keccak_f1600_mm_ip_0_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_timer_1_0/synth/frodoBD_timer_1_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_axi_gpio_0_1/synth/frodoBD_axi_gpio_0_1.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_axi_gpio_3_0/synth/frodoBD_axi_gpio_3_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_axi_gpio_4_0/synth/frodoBD_axi_gpio_4_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/src/controller.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/hdl/matrix_sa_plus_e_mm_ip_v1_0_S00_AXI.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/hdl/matrix_sa_plus_e_mm_ip_v1_0_S01_AXI.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/hdl/matrix_sa_plus_e_mm_ip_v1_0_S02_AXI.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/src/multiplicator.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/src/true_dual_bram.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/src/true_single_bram.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/b8f6/hdl/matrix_sa_plus_e_mm_ip_v1_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_matrix_sa_plus_e_mm_ip_0_0/synth/frodoBD_matrix_sa_plus_e_mm_ip_0_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/27a5/hdl/controller2.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/27a5/hdl/matrix_as_plus_e_mm_ip_v1_0_S00_AXI.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/27a5/hdl/matrix_as_plus_e_mm_ip_v1_0_S01_AXI.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/27a5/hdl/matrix_as_plus_e_mm_ip_v1_0_S02_AXI.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/27a5/hdl/multiplicator2.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/27a5/hdl/true_single_bram2.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/27a5/hdl/matrix_as_plus_e_mm_ip_v1_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_matrix_as_plus_e_mm_0_0/synth/frodoBD_matrix_as_plus_e_mm_0_0.vhd
      c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ip/frodoBD_axi_gpio_5_0/synth/frodoBD_axi_gpio_5_0.vhd
      C:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/synth/frodoBD.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_3 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/c001/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_4 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/1f5a/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_21 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/9c6e/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_13 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/4dac/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_fifo_mm_s_v4_2_1 c:/Projects/frodo-fpga/frodo-fpga.srcs/sources_1/bd/frodoBD/ipshared/fd10/hdl/axi_fifo_mm_s_v4_2_rfs.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Projects/frodo-fpga/frodo-fpga.runs/synth_1/.Xil/Vivado-18240-Vinicius-PC/realtime/frodoBD_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top frodoBD_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Projects/frodo-fpga/frodo-fpga.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Projects/frodo-fpga/frodo-fpga.runs/synth_1/.Xil/Vivado-18240-Vinicius-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
