# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/frodoBD/frodoBD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD || ORIG_REF_NAME==frodoBD} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_processing_system7_0_0/frodoBD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_processing_system7_0_0 || ORIG_REF_NAME==frodoBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_proc_sys_reset_0_0/frodoBD_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_proc_sys_reset_0_0 || ORIG_REF_NAME==frodoBD_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_xbar_0/frodoBD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_xbar_0 || ORIG_REF_NAME==frodoBD_xbar_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_interconnect_0_0/frodoBD_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_interconnect_0_0 || ORIG_REF_NAME==frodoBD_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_4_0/frodoBD_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_4_0 || ORIG_REF_NAME==frodoBD_axi_gpio_4_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_matrix_sa_plus_e_mm_ip_0_0/frodoBD_matrix_sa_plus_e_mm_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_matrix_sa_plus_e_mm_ip_0_0 || ORIG_REF_NAME==frodoBD_matrix_sa_plus_e_mm_ip_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_matrix_as_plus_e_mm_0_0/frodoBD_matrix_as_plus_e_mm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_matrix_as_plus_e_mm_0_0 || ORIG_REF_NAME==frodoBD_matrix_as_plus_e_mm_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_5_0/frodoBD_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_5_0 || ORIG_REF_NAME==frodoBD_axi_gpio_5_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_2_0/frodoBD_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_2_0 || ORIG_REF_NAME==frodoBD_timer_2_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_3_0/frodoBD_timer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_3_0 || ORIG_REF_NAME==frodoBD_timer_3_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_0_3/frodoBD_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_3 || ORIG_REF_NAME==frodoBD_axi_gpio_0_3} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_1_0 || ORIG_REF_NAME==frodoBD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_4_0/frodoBD_timer_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_4_0 || ORIG_REF_NAME==frodoBD_timer_4_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_5_0/frodoBD_timer_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_5_0 || ORIG_REF_NAME==frodoBD_timer_5_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_4_1/frodoBD_axi_gpio_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_4_1 || ORIG_REF_NAME==frodoBD_axi_gpio_4_1} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_7_0/frodoBD_axi_gpio_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_7_0 || ORIG_REF_NAME==frodoBD_axi_gpio_7_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_shake128_ip_0_0/frodoBD_shake128_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_shake128_ip_0_0 || ORIG_REF_NAME==frodoBD_shake128_ip_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_6_0/frodoBD_timer_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_6_0 || ORIG_REF_NAME==frodoBD_timer_6_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_7_0/frodoBD_timer_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_7_0 || ORIG_REF_NAME==frodoBD_timer_7_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_8_1/frodoBD_axi_gpio_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_8_1 || ORIG_REF_NAME==frodoBD_axi_gpio_8_1} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_9_0/frodoBD_axi_gpio_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_9_0 || ORIG_REF_NAME==frodoBD_axi_gpio_9_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_10_0/frodoBD_axi_gpio_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_10_0 || ORIG_REF_NAME==frodoBD_axi_gpio_10_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_11_0/frodoBD_axi_gpio_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_11_0 || ORIG_REF_NAME==frodoBD_axi_gpio_11_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_8_0/frodoBD_timer_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_8_0 || ORIG_REF_NAME==frodoBD_timer_8_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_12_0/frodoBD_axi_gpio_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_12_0 || ORIG_REF_NAME==frodoBD_axi_gpio_12_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_13_0/frodoBD_axi_gpio_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_13_0 || ORIG_REF_NAME==frodoBD_axi_gpio_13_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_0_0/frodoBD_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_0_0 || ORIG_REF_NAME==frodoBD_timer_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_0_4/frodoBD_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_4 || ORIG_REF_NAME==frodoBD_axi_gpio_0_4} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_3_0 || ORIG_REF_NAME==frodoBD_axi_gpio_3_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_tier2_xbar_0_0/frodoBD_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_tier2_xbar_0_0 || ORIG_REF_NAME==frodoBD_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_tier2_xbar_1_0/frodoBD_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_tier2_xbar_1_0 || ORIG_REF_NAME==frodoBD_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_tier2_xbar_2_0/frodoBD_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_tier2_xbar_2_0 || ORIG_REF_NAME==frodoBD_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_auto_pc_0/frodoBD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_auto_pc_0 || ORIG_REF_NAME==frodoBD_auto_pc_0} -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_processing_system7_0_0/frodoBD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_processing_system7_0_0 || ORIG_REF_NAME==frodoBD_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_proc_sys_reset_0_0/frodoBD_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_proc_sys_reset_0_0 || ORIG_REF_NAME==frodoBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_proc_sys_reset_0_0/frodoBD_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_proc_sys_reset_0_0 || ORIG_REF_NAME==frodoBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_4_0/frodoBD_axi_gpio_4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_4_0 || ORIG_REF_NAME==frodoBD_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_4_0/frodoBD_axi_gpio_4_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_4_0/frodoBD_axi_gpio_4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_4_0 || ORIG_REF_NAME==frodoBD_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_5_0/frodoBD_axi_gpio_5_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_5_0 || ORIG_REF_NAME==frodoBD_axi_gpio_5_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_5_0/frodoBD_axi_gpio_5_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_5_0/frodoBD_axi_gpio_5_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_5_0 || ORIG_REF_NAME==frodoBD_axi_gpio_5_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_3/frodoBD_axi_gpio_0_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_3 || ORIG_REF_NAME==frodoBD_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_3/frodoBD_axi_gpio_0_3_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_3/frodoBD_axi_gpio_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_3 || ORIG_REF_NAME==frodoBD_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_1_0 || ORIG_REF_NAME==frodoBD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_1_0 || ORIG_REF_NAME==frodoBD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_4_1/frodoBD_axi_gpio_4_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_4_1 || ORIG_REF_NAME==frodoBD_axi_gpio_4_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_4_1/frodoBD_axi_gpio_4_1_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_4_1/frodoBD_axi_gpio_4_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_4_1 || ORIG_REF_NAME==frodoBD_axi_gpio_4_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_7_0/frodoBD_axi_gpio_7_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_7_0 || ORIG_REF_NAME==frodoBD_axi_gpio_7_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_7_0/frodoBD_axi_gpio_7_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_7_0/frodoBD_axi_gpio_7_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_7_0 || ORIG_REF_NAME==frodoBD_axi_gpio_7_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_8_1/frodoBD_axi_gpio_8_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_8_1 || ORIG_REF_NAME==frodoBD_axi_gpio_8_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_8_1/frodoBD_axi_gpio_8_1_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_8_1/frodoBD_axi_gpio_8_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_8_1 || ORIG_REF_NAME==frodoBD_axi_gpio_8_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_9_0/frodoBD_axi_gpio_9_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_9_0 || ORIG_REF_NAME==frodoBD_axi_gpio_9_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_9_0/frodoBD_axi_gpio_9_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_9_0/frodoBD_axi_gpio_9_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_9_0 || ORIG_REF_NAME==frodoBD_axi_gpio_9_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_10_0/frodoBD_axi_gpio_10_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_10_0 || ORIG_REF_NAME==frodoBD_axi_gpio_10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_10_0/frodoBD_axi_gpio_10_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_10_0/frodoBD_axi_gpio_10_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_10_0 || ORIG_REF_NAME==frodoBD_axi_gpio_10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_11_0/frodoBD_axi_gpio_11_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_11_0 || ORIG_REF_NAME==frodoBD_axi_gpio_11_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_11_0/frodoBD_axi_gpio_11_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_11_0/frodoBD_axi_gpio_11_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_11_0 || ORIG_REF_NAME==frodoBD_axi_gpio_11_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_12_0/frodoBD_axi_gpio_12_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_12_0 || ORIG_REF_NAME==frodoBD_axi_gpio_12_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_12_0/frodoBD_axi_gpio_12_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_12_0/frodoBD_axi_gpio_12_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_12_0 || ORIG_REF_NAME==frodoBD_axi_gpio_12_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_13_0/frodoBD_axi_gpio_13_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_13_0 || ORIG_REF_NAME==frodoBD_axi_gpio_13_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_13_0/frodoBD_axi_gpio_13_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_13_0/frodoBD_axi_gpio_13_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_13_0 || ORIG_REF_NAME==frodoBD_axi_gpio_13_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_4/frodoBD_axi_gpio_0_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_4 || ORIG_REF_NAME==frodoBD_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_4/frodoBD_axi_gpio_0_4_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_4/frodoBD_axi_gpio_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_4 || ORIG_REF_NAME==frodoBD_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_3_0 || ORIG_REF_NAME==frodoBD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_3_0 || ORIG_REF_NAME==frodoBD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_tier2_xbar_0_0/frodoBD_tier2_xbar_0_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_tier2_xbar_1_0/frodoBD_tier2_xbar_1_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_tier2_xbar_2_0/frodoBD_tier2_xbar_2_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_auto_pc_0/frodoBD_auto_pc_0_ooc.xdc

# XDC: bd/frodoBD/frodoBD_ooc.xdc
