# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/frodoBD/frodoBD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD || ORIG_REF_NAME==frodoBD} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_processing_system7_0_0/frodoBD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_processing_system7_0_0 || ORIG_REF_NAME==frodoBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_proc_sys_reset_0_0/frodoBD_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_proc_sys_reset_0_0 || ORIG_REF_NAME==frodoBD_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_xbar_0/frodoBD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_xbar_0 || ORIG_REF_NAME==frodoBD_xbar_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_interconnect_0_0/frodoBD_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_interconnect_0_0 || ORIG_REF_NAME==frodoBD_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_1_0 || ORIG_REF_NAME==frodoBD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_fifo_mm_s_0_0/frodoBD_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==frodoBD_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_2_0/frodoBD_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_2_0 || ORIG_REF_NAME==frodoBD_axi_gpio_2_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_0_2/frodoBD_timer_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_0_2 || ORIG_REF_NAME==frodoBD_timer_0_2} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_keccak_f1600_ip_0_0/frodoBD_keccak_f1600_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_keccak_f1600_ip_0_0 || ORIG_REF_NAME==frodoBD_keccak_f1600_ip_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_keccak_f1600_mm_ip_0_0/frodoBD_keccak_f1600_mm_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_keccak_f1600_mm_ip_0_0 || ORIG_REF_NAME==frodoBD_keccak_f1600_mm_ip_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_timer_1_0/frodoBD_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_timer_1_0 || ORIG_REF_NAME==frodoBD_timer_1_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_0_1/frodoBD_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_1 || ORIG_REF_NAME==frodoBD_axi_gpio_0_1} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_3_0 || ORIG_REF_NAME==frodoBD_axi_gpio_3_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_mult_add_sa_plus_e_m_0_0/frodoBD_mult_add_sa_plus_e_m_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_mult_add_sa_plus_e_m_0_0 || ORIG_REF_NAME==frodoBD_mult_add_sa_plus_e_m_0_0} -quiet] -quiet

# IP: bd/frodoBD/ip/frodoBD_auto_pc_0/frodoBD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frodoBD_auto_pc_0 || ORIG_REF_NAME==frodoBD_auto_pc_0} -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_processing_system7_0_0/frodoBD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_processing_system7_0_0 || ORIG_REF_NAME==frodoBD_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_proc_sys_reset_0_0/frodoBD_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_proc_sys_reset_0_0 || ORIG_REF_NAME==frodoBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_proc_sys_reset_0_0/frodoBD_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_proc_sys_reset_0_0 || ORIG_REF_NAME==frodoBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_1_0 || ORIG_REF_NAME==frodoBD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_1_0/frodoBD_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_1_0 || ORIG_REF_NAME==frodoBD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_fifo_mm_s_0_0/frodoBD_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_2_0/frodoBD_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_2_0 || ORIG_REF_NAME==frodoBD_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_2_0/frodoBD_axi_gpio_2_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_2_0/frodoBD_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_2_0 || ORIG_REF_NAME==frodoBD_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_1/frodoBD_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_1 || ORIG_REF_NAME==frodoBD_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_1/frodoBD_axi_gpio_0_1_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_0_1/frodoBD_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_0_1 || ORIG_REF_NAME==frodoBD_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_3_0 || ORIG_REF_NAME==frodoBD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0_ooc.xdc

# XDC: bd/frodoBD/ip/frodoBD_axi_gpio_3_0/frodoBD_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==frodoBD_axi_gpio_3_0 || ORIG_REF_NAME==frodoBD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/frodoBD/ip/frodoBD_auto_pc_0/frodoBD_auto_pc_0_ooc.xdc

# XDC: bd/frodoBD/frodoBD_ooc.xdc
